# Allow GUI apps to scale based on DPI.
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# Merge the xresources file.
xrdb -load /archlinux/config/X/xresources

# Start the compositor (for blurring, opacity).
xcompmgr &

# Set keyboard layout.
setxkbmap hu

# Merge keyboard modifications.
xmodmap /archlinux/config/X/xmodmap

# Set wallpaper.
/archlinux/scripts/wallpaper.fish simple

exec i3
