# Scale some GUI apps.
export GDK_SCALE=1
export GDK_DPI_SCALE=0.95
export QT_SCREEN_SCALE_FACTOR=0.9
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=1

# Merge the xresources file.
xrdb -merge ~/.config/X11/xresources

exec i3
